//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_OOP_version1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_OOP_version1.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ЗАБОРОНА] Спочатку ініціюйте проект (Пункт 3)!.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть дію:.
        /// </summary>
        public static string EnterChoice {
            get {
                return ResourceManager.GetString("EnterChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Переглянути склад команди.
        /// </summary>
        public static string MenuAction1 {
            get {
                return ResourceManager.GetString("MenuAction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Додати нового автора в базу даних.
        /// </summary>
        public static string MenuAction10 {
            get {
                return ResourceManager.GetString("MenuAction10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Видалити автора з бази даних.
        /// </summary>
        public static string MenuAction11 {
            get {
                return ResourceManager.GetString("MenuAction11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. Вихід.
        /// </summary>
        public static string MenuAction12 {
            get {
                return ResourceManager.GetString("MenuAction12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Додати фахівця до команди.
        /// </summary>
        public static string MenuAction2 {
            get {
                return ResourceManager.GetString("MenuAction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Ініціювати проект.
        /// </summary>
        public static string MenuAction3 {
            get {
                return ResourceManager.GetString("MenuAction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Створити стартап-ідею та запустити аналіз доцільності.
        /// </summary>
        public static string MenuAction4 {
            get {
                return ResourceManager.GetString("MenuAction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Розробити бізнес-модель Canvas.
        /// </summary>
        public static string MenuAction5 {
            get {
                return ResourceManager.GetString("MenuAction5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Розрахувати фінансовий бізнес-план.
        /// </summary>
        public static string MenuAction6 {
            get {
                return ResourceManager.GetString("MenuAction6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Презентувати проект інвесторам (Пошук фінансування).
        /// </summary>
        public static string MenuAction7 {
            get {
                return ResourceManager.GetString("MenuAction7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Повна автоматична симуляція циклу.
        /// </summary>
        public static string MenuAction8 {
            get {
                return ResourceManager.GetString("MenuAction8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.Переглянути авторів з бази даних.
        /// </summary>
        public static string MenuAction9 {
            get {
                return ResourceManager.GetString("MenuAction9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === СТАРТАП-ПЛАТФОРМА: ВЕРСІЯ 6.0 (Фінальна Інтеграція) ===.
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==================================================\n АВТОМАТИЧНУ СИМУЛЯЦІЮ УСПІШНО ЗАВЕРШЕНО \n==================================================\n.
        /// </summary>
        public static string SimulationEnd {
            get {
                return ResourceManager.GetString("SimulationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n==================================================\n ЗАПУСК ПОВНОГО АВТОМАТИЗОВАНОГО ЦИКЛУ СТАРТАПУ \n==================================================\n.
        /// </summary>
        public static string SimulationStart {
            get {
                return ResourceManager.GetString("SimulationStart", resourceCulture);
            }
        }
    }
}
